### PR TITLE
Added Fibonacci Series

### PR DESCRIPTION
**Pull request by blog-a1**

### CODE REVIEW

**Review by sugandha-kadp — COMMENTED** [review]
Original code is related find Factorial, but you have pull another one

**Comment by blog-a1** [comment]
Sorry for that, I was trying to add some more questions.

**Comment by sugandha-kadp** [comment]
If you want to add more, you can make a new file. This basically makes for hacktoberfest beginners.

**Comment by blog-a1** [comment]
OK

**Pull request closed without merging**
