### PR TITLE
Update Factorial.c

### PR DESCRIPTION
**Pull request by harshitgupta028**
Please check it.

### CODE REVIEW

**Comment by harshitgupta028** [comment]
Extension of the file changed from c to CPP

**Comment by harshitgupta028** [comment]
Please mark "hacktoberfest-accepted" again.
Thank you.

**Comment by sugandha-kadp** [comment]
file is already accepted

**Comment by harshitgupta028** [comment]
ok thanks.

**Comment by sugandha-kadp** [comment]
You're Welcome

**Pull request closed without merging**
